#######################################################################################
# Book settings
title: "Remote Computational Project Resource"
author: "Isabel Birds"

#######################################################################################
# Execution settings
execute:
  execute_notebooks: "off"

#######################################################################################
# Launch button settings

repository:
  url                       : https://github.com/IsabelBirds/Undergrad_Project_Resource
  path_to_book              : "book/"
html:
  use_repository_button     : true
  use_issues_button         : true
  use_edit_page_button      : true
#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :  
  config                    :  
    language                : en