name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
      - master
  pull_request:
     branches:
      - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build ./book
        
    - name: Run html proofer
      uses: chabad360/htmlproofer@master
      with:
        directory: "./book/_build/html"
        arguments: --assume-extension --disable-external --only_4xx
      continue-on-error: true
   
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book/_build/html
